# Generated by Django 6.0 on 2026-01-19 03:45

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfilactivo', models.IntegerField(choices=[(1, 'Perfil profesional'), (2, 'Perfil alternativo'), (3, 'Perfil personal')], verbose_name='Tipo perfil')),
                ('es_activo', models.BooleanField(default=False, verbose_name='Perfil activo')),
                ('descripcionperfil', models.CharField(max_length=100, verbose_name='Descripción del perfil')),
                ('apellidos', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('nombres', models.CharField(max_length=60, verbose_name='Nombres')),
                ('foto_perfil', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto_perfil')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('lugarnacimiento', models.CharField(blank=True, max_length=60, verbose_name='Lugar de nacimiento')),
                ('fechanacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('numerocedula', models.CharField(max_length=10, unique=True, verbose_name='Número de cédula')),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, verbose_name='Sexo')),
                ('estadocivil', models.CharField(max_length=50, verbose_name='Estado civil')),
                ('licenciaconducir', models.CharField(blank=True, max_length=6, null=True, verbose_name='Licencia de conducir')),
                ('telefonoconvencional', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono convencional')),
                ('telefonofijo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono fijo')),
                ('direcciontrabajo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección de trabajo')),
                ('direcciondomiciliaria', models.CharField(blank=True, max_length=50, verbose_name='Dirección domiciliaria')),
                ('sitioweb', models.CharField(blank=True, max_length=60, null=True, verbose_name='Sitio web')),
            ],
            options={
                'verbose_name': 'Datos personales',
                'verbose_name_plural': 'Datos personales',
            },
        ),
        migrations.CreateModel(
            name='CursosRealizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecurso', models.CharField(max_length=100, verbose_name='Nombre del curso')),
                ('fechainicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fechafin', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('totalhoras', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total de horas')),
                ('descripcioncurso', models.CharField(blank=True, max_length=100, verbose_name='Descripción del curso')),
                ('entidadpatrocinadora', models.CharField(blank=True, max_length=100, verbose_name='Entidad patrocinadora')),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, verbose_name='Nombre del contacto que auspicia')),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, verbose_name='Teléfono del contacto')),
                ('emailempresapatrocinadora', models.EmailField(blank=True, max_length=254, verbose_name='Email de la entidad patrocinadora')),
                ('certificado', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificado')),
                ('imagen_certificado', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen del certificado')),
                ('activar_para_front', models.BooleanField(default=True, verbose_name='Mostrar en la página web')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_realizados', to='hojadevida.datospersonales', verbose_name='Perfil al que pertenece')),
            ],
            options={
                'verbose_name': 'Curso realizado',
                'verbose_name_plural': 'Cursos realizados',
                'ordering': ['-fechainicio'],
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_desempenado', models.CharField(max_length=100, verbose_name='Cargo desempeñado')),
                ('nombre_empresa', models.CharField(max_length=50, verbose_name='Nombre de la empresa')),
                ('lugar_empresa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lugar de la empresa')),
                ('email_empresa', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de la empresa')),
                ('sitio_web_empresa', models.URLField(blank=True, null=True, verbose_name='Sitio web de la empresa')),
                ('nombre_contacto_empresarial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del contacto empresarial')),
                ('telefono_contacto_empresarial', models.CharField(blank=True, max_length=60, null=True, verbose_name='Teléfono del contacto')),
                ('fecha_inicio_gestion', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin_gestion', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('descripcion_funciones', models.TextField(blank=True, verbose_name='Descripción de funciones')),
                ('certificado', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificado')),
                ('imagen_certificado', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen del certificado')),
                ('activar_para_front', models.BooleanField(default=True, verbose_name='Mostrar en la página web')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='hojadevida.datospersonales', verbose_name='Perfil al que pertenece')),
            ],
            options={
                'verbose_name': 'Experiencia laboral',
                'verbose_name_plural': 'Experiencias laborales',
                'ordering': ['-fecha_inicio_gestion'],
            },
        ),
        migrations.CreateModel(
            name='ProductosAcademicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrerecurso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del recurso')),
                ('clasificador', models.CharField(blank=True, max_length=100, verbose_name='Clasificador')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Imagen del producto')),
                ('activar_para_front', models.BooleanField(default=True, verbose_name='Mostrar en la página')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='hojadevida.datospersonales', verbose_name='Perfil al que pertenece')),
            ],
            options={
                'verbose_name': 'Producto académico',
                'verbose_name_plural': 'Productos académicos',
            },
        ),
        migrations.CreateModel(
            name='ProductosLaborales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(blank=True, max_length=100, verbose_name='Nombre del producto')),
                ('tipoproducto', models.CharField(blank=True, max_length=100, verbose_name='Tipo de producto')),
                ('fecha_producto', models.DateField(verbose_name='Fecha de creación del producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activar_para_front', models.BooleanField(default=True, verbose_name='Mostrar en la página')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_laborales', to='hojadevida.datospersonales', verbose_name='Perfil al que pertenece')),
            ],
            options={
                'verbose_name': 'Producto laboral',
                'verbose_name_plural': 'Productos laborales',
            },
        ),
        migrations.CreateModel(
            name='Reconocimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiporeconocimiento', models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=100, verbose_name='Tipo de reconocimiento')),
                ('fechareconocimiento', models.DateField(verbose_name='Fecha del reconocimiento')),
                ('descripcionreconocimiento', models.CharField(blank=True, max_length=100, verbose_name='Descripción del reconocimiento')),
                ('entidadpatrocinadora', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entidad patrocinadora')),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del contacto que auspicia')),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, null=True, verbose_name='Teléfono del contacto que auspicia')),
                ('certificado', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificado')),
                ('imagen_certificado', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen del certificado')),
                ('activar_para_front', models.BooleanField(default=True, verbose_name='Mostrar en la página web')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='hojadevida.datospersonales', verbose_name='Perfil al que pertenece')),
            ],
            options={
                'verbose_name': 'Reconocimiento',
                'verbose_name_plural': 'Reconocimientos',
                'ordering': ['-fechareconocimiento'],
            },
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('estadoproducto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40, verbose_name='Estado del producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('valordelbien', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Valor del bien')),
                ('imagen', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen del producto')),
                ('activar_para_front', models.BooleanField(default=True, verbose_name='Mostrar en la página')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta_garage', to='hojadevida.datospersonales', verbose_name='Perfil al que pertenece')),
            ],
            options={
                'verbose_name': 'Venta de garage',
                'verbose_name_plural': 'Venta de garage',
            },
        ),
    ]
