# Generated by Django 6.0 on 2026-01-27 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoslaborales',
            options={
                'ordering': ['-fecha_producto'],
                'verbose_name': 'Producto laboral',
                'verbose_name_plural': 'Productos laborales'
            },
        ),
        migrations.AlterModelOptions(
            name='ventagarage',
            options={
                'ordering': ['-fecha_publicacion'],
                'verbose_name': 'Venta de garage',
                'verbose_name_plural': 'Venta de garage'
            },
        ),
    ]
