# Generated by Django 6.0 on 2026-01-19 22:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosacademicos',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen del producto'),
        ),
    ]
