# Generated by Django 6.0 on 2026-01-27 00:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoslaborales',
            options={'ordering': ['-fecha_producto'], 'verbose_name': 'Producto laboral', 'verbose_name_plural': 'Productos laborales'},
        ),
        migrations.AlterModelOptions(
            name='ventagarage',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name': 'Venta de garage', 'verbose_name_plural': 'Venta de garage'},
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
            preserve_default=False,
        ),
    ]
