# Generated by Django 6.0 on 2026-01-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0002_alter_productosacademicos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='descripcioncurso',
            field=models.TextField(blank=True, verbose_name='Descripción del curso'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='descripcionreconocimiento',
            field=models.TextField(blank=True, verbose_name='Descripción del reconocimiento'),
        ),
    ]
