# Generated by Django 6.0 on 2025-12-24 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0002_alter_datospersonales_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='perfilactivo',
            field=models.IntegerField(choices=[(1, 'Perfil Profesional'), (2, 'Perfil Alternativo'), (3, 'Perfil Personal')]),
        ),
        migrations.CreateModel(
            name='PerfilDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.IntegerField(choices=[(1, 'Perfil Profesional'), (2, 'Perfil Alternativo'), (3, 'Perfil Personal')])),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='hojadevida.datospersonales')),
            ],
        ),
    ]
