# Generated by Django 6.0 on 2025-12-24 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0003_alter_datospersonales_perfilactivo_perfildetalle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerfilDetalle',
            new_name='QuePerfilActivo',
        ),
    ]
