# Generated by Django 6.0 on 2025-12-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0004_rename_perfildetalle_queperfilactivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queperfilactivo',
            name='titulo',
        ),
        migrations.AddField(
            model_name='queperfilactivo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='queperfilactivo',
            name='perfil',
            field=models.IntegerField(choices=[(1, 'Perfil profesional'), (2, 'Perfil académico'), (3, 'Perfil personal')]),
        ),
    ]
