# Generated by Django 6.0 on 2025-12-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0005_remove_queperfilactivo_titulo_queperfilactivo_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='tipoperfil',
            field=models.IntegerField(choices=[(1, 'Perfil profesional'), (2, 'Perfil alternativo'), (3, 'Perfil personal')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='perfilactivo',
            field=models.IntegerField(choices=[(1, 'Perfil profesional'), (2, 'Perfil alternativo'), (3, 'Perfil personal')]),
        ),
        migrations.DeleteModel(
            name='QuePerfilActivo',
        ),
    ]
