# Generated by Django 6.0 on 2025-12-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0006_datospersonales_tipoperfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonales',
            name='tipoperfil',
        ),
    ]
