# Generated by Django 6.0 on 2025-12-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0007_remove_datospersonales_tipoperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='tipoperfil',
            field=models.IntegerField(choices=[(1, 'Perfil profesional'), (2, 'Perfil alternativo'), (3, 'Perfil personal')], default=1),
            preserve_default=False,
        ),
    ]
