# Generated by Django 6.0 on 2025-12-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0008_datospersonales_tipoperfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonales',
            name='tipoperfil',
        ),
    ]
