# Generated by Django 6.0 on 2025-12-26 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0009_remove_datospersonales_tipoperfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_desempenado', models.CharField(max_length=100)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('lugar_empresa', models.CharField(blank=True, max_length=50)),
                ('email_empresa', models.EmailField(blank=True, max_length=254)),
                ('sitio_web_empresa', models.URLField(blank=True)),
                ('nombre_contacto_empresarial', models.CharField(blank=True, max_length=100)),
                ('telefono_contacto_empresarial', models.CharField(blank=True, max_length=60)),
                ('fecha_inicio_gestion', models.DateField()),
                ('fecha_fin_gestion', models.DateField(blank=True, null=True)),
                ('descripcion_funciones', models.TextField(blank=True)),
                ('activar_para_front', models.BooleanField(default=True)),
                ('ruta_certificado', models.CharField(blank=True, max_length=100)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='hojadevida.datospersonales')),
            ],
            options={
                'ordering': ['-fecha_inicio_gestion'],
            },
        ),
    ]
