# Generated by Django 6.0 on 2025-12-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0010_experiencialaboral'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='mostrar_cargo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='mostrar_descripcion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='mostrar_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='mostrar_empresa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='mostrar_lugar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='mostrar_sitio_web',
            field=models.BooleanField(default=False),
        ),
    ]
