# Generated by Django 6.0 on 2025-12-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0011_experiencialaboral_mostrar_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='mostrar_nombre_contacto',
            field=models.BooleanField(default=True),
        ),
    ]
