# Generated by Django 6.0 on 2025-12-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0012_experiencialaboral_mostrar_nombre_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciondomiciliaria',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciontrabajo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='estadocivil',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='licenciaconducir',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='lugarnacimiento',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sitioweb',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonoconvencional',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonofijo',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
