# Generated by Django 6.0 on 2025-12-26 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0013_alter_datospersonales_direcciondomiciliaria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datospersonales',
            old_name='estadocivil',
            new_name='estado_civil',
        ),
    ]
