# Generated by Django 6.0 on 2025-12-26 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0014_rename_estadocivil_datospersonales_estado_civil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datospersonales',
            old_name='descripcionperfil',
            new_name='descripcion_perfil',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='direcciondomiciliaria',
            new_name='direccion_domiciliaria',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='direcciontrabajo',
            new_name='direccion_trabajo',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='fechanacimiento',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='licenciaconducir',
            new_name='licencia_conducir',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='lugarnacimiento',
            new_name='lugar_nacimiento',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='numerocedula',
            new_name='numero_cedula',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='perfilactivo',
            new_name='perfil_activo',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='sitioweb',
            new_name='sitio_web',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='telefonoconvencional',
            new_name='telefono_convencional',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='telefonofijo',
            new_name='telefono_fijo',
        ),
    ]
