# Generated by Django 6.0 on 2025-12-26 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0015_rename_descripcionperfil_datospersonales_descripcion_perfil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datospersonales',
            old_name='descripcion_perfil',
            new_name='descripcionperfil',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='direccion_domiciliaria',
            new_name='direcciondomiciliaria',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='direccion_trabajo',
            new_name='direcciontrabajo',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='estado_civil',
            new_name='estadocivil',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='fecha_nacimiento',
            new_name='fechanacimiento',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='licencia_conducir',
            new_name='licenciaconducir',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='lugar_nacimiento',
            new_name='lugarnacimiento',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='numero_cedula',
            new_name='numerocedula',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='perfil_activo',
            new_name='perfilactivo',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='sitio_web',
            new_name='sitioweb',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='telefono_convencional',
            new_name='telefonoconvencional',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='telefono_fijo',
            new_name='telefonofijo',
        ),
    ]
