# Generated by Django 6.0 on 2025-12-26 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0016_rename_descripcion_perfil_datospersonales_descripcionperfil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datospersonales',
            old_name='descripcionperfil',
            new_name='descripcion_perfil',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='perfilactivo',
            new_name='perfil_activo',
        ),
    ]
