# Generated by Django 6.0 on 2025-12-26 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0017_rename_descripcionperfil_datospersonales_descripcion_perfil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datospersonales',
            old_name='descripcion_perfil',
            new_name='descripcionperfil',
        ),
        migrations.RenameField(
            model_name='datospersonales',
            old_name='perfil_activo',
            new_name='perfilactivo',
        ),
    ]
