# Generated by Django 6.0 on 2025-12-26 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0019_rename_perfilactivo_datospersonales_perfil_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datospersonales',
            old_name='perfil_activo',
            new_name='perfilactivo',
        ),
    ]
