# Generated by Django 6.0 on 2025-12-26 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0021_alter_datospersonales_apellidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiporeconocimiento', models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=100)),
                ('fechareconocimiento', models.DateField()),
                ('descripcionreconocimiento', models.CharField(blank=True, max_length=100)),
                ('entidadpatrocinadora', models.CharField(blank=True, max_length=100)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=100)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='hojadevida.datospersonales')),
            ],
            options={
                'ordering': ['-fechareconocimiento'],
            },
        ),
        migrations.DeleteModel(
            name='RECONOCIMIENTOS',
        ),
    ]
