# Generated by Django 6.0 on 2025-12-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0022_reconocimiento_delete_reconocimientos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reconocimiento',
            new_name='Reconocimientos',
        ),
    ]
