# Generated by Django 6.0 on 2025-12-26 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0023_rename_reconocimiento_reconocimientos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reconocimientos',
            options={'ordering': ['-fechareconocimiento'], 'verbose_name': 'Reconocimiento', 'verbose_name_plural': 'Reconocimientos'},
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=True, verbose_name='Mostrar en la página web'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='descripcionreconocimiento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Descripción del reconocimiento'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='entidadpatrocinadora',
            field=models.CharField(blank=True, max_length=100, verbose_name='Entidad patrocinadora'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='fechareconocimiento',
            field=models.DateField(verbose_name='Fecha del reconocimiento'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='hojadevida.datospersonales', verbose_name='Perfil al que pertenece'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='nombrecontactoauspicia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del contacto que auspicia'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='rutacertificado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ruta del certificado'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='telefonocontactoauspicia',
            field=models.CharField(blank=True, max_length=60, verbose_name='Teléfono del contacto que auspicia'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='tiporeconocimiento',
            field=models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=100, verbose_name='Tipo de reconocimiento'),
        ),
    ]
