# Generated by Django 6.0 on 2025-12-26 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0024_alter_reconocimientos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursosRealizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecurso', models.CharField(max_length=100, verbose_name='Nombre del curso')),
                ('fechainicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fechafin', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('totalhoras', models.IntegerField(blank=True, null=True, verbose_name='Total de horas')),
                ('descripcioncurso', models.CharField(blank=True, max_length=100, verbose_name='Descripción del curso')),
                ('entidadpatrocinadora', models.CharField(blank=True, max_length=100, verbose_name='Entidad patrocinadora')),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, verbose_name='Nombre del contacto que auspicia')),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, verbose_name='Teléfono del contacto')),
                ('emailempresapatrocinadora', models.EmailField(blank=True, max_length=254, verbose_name='Email de la entidad patrocinadora')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Mostrar en la página web')),
                ('rutacertificado', models.CharField(blank=True, max_length=100, verbose_name='Ruta del certificado')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_realizados', to='hojadevida.datospersonales', verbose_name='Perfil al que pertenece')),
            ],
            options={
                'verbose_name': 'Curso realizado',
                'verbose_name_plural': 'Cursos realizados',
                'ordering': ['-fechainicio'],
            },
        ),
    ]
