# Generated by Django 6.0 on 2025-12-26 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0025_cursosrealizados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='totalhoras',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total de horas'),
        ),
    ]
