# Generated by Django 6.0 on 2025-12-26 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0027_productoacademico'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productoacademico',
            table=None,
        ),
    ]
