# Generated by Django 6.0 on 2025-12-26 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0028_alter_productoacademico_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosAcademicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrerecurso', models.CharField(blank=True, max_length=100, verbose_name='Nombre del recurso')),
                ('clasificador', models.CharField(blank=True, max_length=100, verbose_name='Clasificador')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='Descripción')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Mostrar en el frontend')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='hojadevida.datospersonales')),
            ],
        ),
    ]
