# Generated by Django 6.0 on 2025-12-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0029_productosacademicos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoAcademico',
        ),
    ]
