# Generated by Django 6.0 on 2025-12-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0030_delete_productoacademico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosacademicos',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=True, verbose_name='Mostrar en la página'),
        ),
    ]
