# Generated by Django 6.0 on 2025-12-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0031_alter_productosacademicos_activarparaqueseveaenfront'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='perfilactivo',
            field=models.IntegerField(choices=[(1, '1) Perfil profesional'), (2, '2) Perfil alternativo'), (3, '3) Perfil personal')], verbose_name='Perfil activo'),
        ),
    ]
