# Generated by Django 6.0 on 2025-12-27 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0032_alter_datospersonales_perfilactivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosLaborales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(blank=True, max_length=100, verbose_name='Nombre del producto')),
                ('tipoproducto', models.CharField(blank=True, max_length=100, verbose_name='Tipo de producto')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='Descripción')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Mostrar en la página')),
                ('rutadocumento', models.CharField(blank=True, max_length=100, verbose_name='Ruta del documento')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_laborales', to='hojadevida.datospersonales')),
            ],
        ),
    ]
