# Generated by Django 6.0 on 2025-12-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0033_productoslaborales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoslaborales',
            name='rutadocumento',
        ),
    ]
