# Generated by Django 6.0 on 2025-12-27 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0034_remove_productoslaborales_rutadocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='perfilactivo',
            field=models.IntegerField(choices=[(1, '1. Perfil profesional'), (2, '2. Perfil alternativo'), (3, '3. Perfil personal')], verbose_name='Perfil activo'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(blank=True, choices=[('H', 'H'), ('M', 'Mujer')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(blank=True, max_length=100, verbose_name='Nombre del producto')),
                ('estadoproducto', models.CharField(blank=True, choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], max_length=40, verbose_name='Estado del producto')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='Descripción')),
                ('valordelbien', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor del bien')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True, verbose_name='Mostrar en el frontend')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta_garage', to='hojadevida.datospersonales')),
            ],
        ),
    ]
