# Generated by Django 6.0 on 2025-12-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0035_alter_datospersonales_perfilactivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, verbose_name='Sexo'),
        ),
    ]
