# Generated by Django 6.0 on 2025-12-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0036_alter_datospersonales_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventagarage',
            name='estadoproducto',
            field=models.CharField(blank=True, choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40, verbose_name='Estado del producto'),
        ),
    ]
