# Generated by Django 6.0 on 2025-12-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0037_alter_ventagarage_estadoproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventagarage',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=True, verbose_name='Mostrar en la página'),
        ),
    ]
