# Generated by Django 6.0 on 2025-12-27 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0038_alter_ventagarage_activarparaqueseveaenfront'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventagarage',
            name='valordelbien',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Valor del bien'),
        ),
    ]
