# Generated by Django 6.0 on 2025-12-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0039_alter_ventagarage_valordelbien'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='es_activo',
            field=models.BooleanField(default=False, verbose_name='Perfil activo'),
        ),
    ]
