# Generated by Django 6.0 on 2025-12-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0040_datospersonales_es_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='perfilactivo',
            field=models.IntegerField(choices=[(1, '1. Perfil profesional'), (2, '2. Perfil alternativo'), (3, '3. Perfil personal')], verbose_name='Tipo perfil'),
        ),
    ]
