# Generated by Django 6.0 on 2025-12-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0042_alter_datospersonales_direcciontrabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcionperfil',
            field=models.CharField(max_length=100, verbose_name='Descripción del perfil'),
        ),
    ]
