# Generated by Django 6.0 on 2025-12-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0043_alter_datospersonales_descripcionperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='nacionalidad',
            field=models.CharField(default=3, max_length=50, verbose_name='Nacionalidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='email_empresa',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='lugar_empresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='nombre_contacto_empresarial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='ruta_certificado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='sitio_web_empresa',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='telefono_contacto_empresarial',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
