# Generated by Django 6.0 on 2025-12-28 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0044_alter_datospersonales_nacionalidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={'ordering': ['-fecha_inicio_gestion'], 'verbose_name': 'Experiencia laboral', 'verbose_name_plural': 'Experiencias laborales'},
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='mostrar_cargo',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='mostrar_descripcion',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='mostrar_email',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='mostrar_empresa',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='mostrar_lugar',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='mostrar_nombre_contacto',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='mostrar_sitio_web',
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='activar_para_front',
            field=models.BooleanField(default=True, verbose_name='Mostrar en la página web'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='cargo_desempenado',
            field=models.CharField(max_length=100, verbose_name='Cargo desempeñado'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='descripcion_funciones',
            field=models.TextField(blank=True, verbose_name='Descripción de funciones'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='email_empresa',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de la empresa'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fecha_fin_gestion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fecha_inicio_gestion',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='lugar_empresa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lugar de la empresa'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='nombre_contacto_empresarial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del contacto empresarial'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='nombre_empresa',
            field=models.CharField(max_length=50, verbose_name='Nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='hojadevida.datospersonales', verbose_name='Perfil asociado'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='ruta_certificado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ruta del certificado'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='sitio_web_empresa',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio web de la empresa'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='telefono_contacto_empresarial',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Teléfono del contacto'),
        ),
    ]
