# Generated by Django 6.0 on 2025-12-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0045_alter_experiencialaboral_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datospersonales',
            options={'verbose_name': 'Datos personales', 'verbose_name_plural': 'Datos personales'},
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='entidadpatrocinadora',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Entidad patrocinadora'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='nombrecontactoauspicia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del contacto que auspicia'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='rutacertificado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ruta del certificado'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='telefonocontactoauspicia',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Teléfono del contacto que auspicia'),
        ),
    ]
