# Generated by Django 6.0 on 2025-12-28 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0046_alter_datospersonales_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productosacademicos',
            options={'verbose_name': 'Producto académico', 'verbose_name_plural': 'Productos académicos'},
        ),
        migrations.AlterModelOptions(
            name='productoslaborales',
            options={'verbose_name': 'Producto laboral', 'verbose_name_plural': 'Productos laborales'},
        ),
        migrations.AlterModelOptions(
            name='ventagarage',
            options={'verbose_name': 'Venta de garage', 'verbose_name_plural': 'Venta de garage'},
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='descripcion',
            field=models.CharField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='nombrerecurso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del recurso'),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='descripcion',
            field=models.CharField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='descripcion',
            field=models.CharField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='estadoproducto',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40, verbose_name='Estado del producto'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='nombreproducto',
            field=models.CharField(max_length=100, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='valordelbien',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Valor del bien'),
            preserve_default=False,
        ),
    ]
