# Generated by Django 6.0 on 2025-12-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0047_alter_productosacademicos_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencialaboral',
            old_name='perfil',
            new_name='idperfilconqueestaactivo',
        ),
        migrations.RenameField(
            model_name='productosacademicos',
            old_name='perfil',
            new_name='idperfilconqueestaactivo',
        ),
        migrations.RenameField(
            model_name='productoslaborales',
            old_name='perfil',
            new_name='idperfilconqueestaactivo',
        ),
        migrations.RenameField(
            model_name='ventagarage',
            old_name='perfil',
            new_name='idperfilconqueestaactivo',
        ),
    ]
