# Generated by Django 6.0 on 2025-12-28 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0048_rename_perfil_experiencialaboral_idperfilconqueestaactivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencialaboral',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='hojadevida.datospersonales', verbose_name='Perfil al que pertenece'),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='hojadevida.datospersonales', verbose_name='Perfil al que pertenece'),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_laborales', to='hojadevida.datospersonales', verbose_name='Perfil al que pertenece'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta_garage', to='hojadevida.datospersonales', verbose_name='Perfil al que pertenece'),
        ),
    ]
