# Generated by Django 6.0 on 2025-12-29 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0049_alter_experiencialaboral_idperfilconqueestaactivo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursosrealizados',
            old_name='activarparaqueseveaenfront',
            new_name='activar_para_front',
        ),
        migrations.RenameField(
            model_name='productosacademicos',
            old_name='activarparaqueseveaenfront',
            new_name='activar_para_front',
        ),
        migrations.RenameField(
            model_name='productoslaborales',
            old_name='activarparaqueseveaenfront',
            new_name='activar_para_front',
        ),
        migrations.RenameField(
            model_name='reconocimientos',
            old_name='activarparaqueseveaenfront',
            new_name='activar_para_front',
        ),
        migrations.RenameField(
            model_name='ventagarage',
            old_name='activarparaqueseveaenfront',
            new_name='activar_para_front',
        ),
    ]
