# Generated by Django 6.0 on 2025-12-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0050_rename_activarparaqueseveaenfront_cursosrealizados_activar_para_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoslaborales',
            name='fecha_producto',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de creación del producto'),
        ),
    ]
