# Generated by Django 6.0 on 2025-12-30 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0051_productoslaborales_fecha_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoslaborales',
            name='fecha_producto',
            field=models.DateField(default=datetime.date(2025, 12, 30), verbose_name='Fecha de creación del producto'),
            preserve_default=False,
        ),
    ]
