# Generated by Django 6.0 on 2025-12-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0052_alter_productoslaborales_fecha_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='texto_inicio',
            field=models.TextField(blank=True, null=True, verbose_name='Texto de inicio público'),
        ),
    ]
