# Generated by Django 6.0 on 2026-01-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0053_datospersonales_texto_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='perfilactivo',
            field=models.IntegerField(choices=[(1, 'Perfil profesional'), (2, 'Perfil alternativo'), (3, 'Perfil personal')], verbose_name='Tipo perfil'),
        ),
    ]
