# Generated by Django 6.0 on 2026-01-07 02:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0054_alter_datospersonales_perfilactivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursosrealizados',
            name='rutacertificado',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='ruta_certificado',
        ),
        migrations.RemoveField(
            model_name='reconocimientos',
            name='rutacertificado',
        ),
        migrations.AddField(
            model_name='cursosrealizados',
            name='certificado',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificado'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='certificado',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificado'),
        ),
        migrations.AddField(
            model_name='reconocimientos',
            name='certificado',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificado'),
        ),
    ]
