# Generated by Django 6.0 on 2026-01-07 16:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0055_remove_cursosrealizados_rutacertificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto_perfil'),
        ),
    ]
