# Generated by Django 6.0 on 2026-01-10 22:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0056_datospersonales_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosacademicos',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Imagen del producto'),
        ),
    ]
