# Generated by Django 6.0 on 2026-01-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0057_productosacademicos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='venta_garage/', verbose_name='Imagen del producto'),
        ),
    ]
