# Generated by Django 6.0 on 2026-01-11 06:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0058_ventagarage_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventagarage',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen del producto'),
        ),
    ]
